// <auto-generated />
using System;
using GuitarStore.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GuitarStore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240616081016_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("GuitarStore.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomerType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Accounts");

                    b.HasDiscriminator<string>("CustomerType").HasValue("Account");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("GuitarStore.Models.Customer", b =>
                {
                    b.HasBaseType("GuitarStore.Models.Account");

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Customer");
                });

            modelBuilder.Entity("GuitarStore.Models.Employee", b =>
                {
                    b.HasBaseType("GuitarStore.Models.Account");

                    b.Property<int>("CommissionRate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContractNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Positions")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PrivilegeLevel")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("Employee");
                });

            modelBuilder.Entity("GuitarStore.Models.RegularCustomer", b =>
                {
                    b.HasBaseType("GuitarStore.Models.Customer");

                    b.HasDiscriminator().HasValue("Regular");
                });

            modelBuilder.Entity("GuitarStore.Models.TrustedCustomer", b =>
                {
                    b.HasBaseType("GuitarStore.Models.Customer");

                    b.Property<DateTime>("StatusExpiryDate")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Trusted");
                });
#pragma warning restore 612, 618
        }
    }
}
